SELECT kk.NAME ,z.ID, z.VSEGO FROM ZEM z
	JOIN KPU_CATAL kc ON kc.ID = z.ID_CATAL
	JOIN KNIGA_KATO kk ON kk.ID = kc.KATO_ID
	ROWS 1;

SELECT sum(VSEGO) FROM ZEM
	WHERE ID_CATAL IN (SELECT id FROM KPU_CATAL WHERE KATO_ID IN (255831));

SELECT sum(vsego) FROM ZEM
	WHERE ID_CATAL IN (SELECT id FROM KPU_CATAL);